/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as BstRouteImport } from './routes/bst'
import { Route as IndexRouteImport } from './routes/index'

const BstRoute = BstRouteImport.update({
  id: '/bst',
  path: '/bst',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/bst': typeof BstRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/bst': typeof BstRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/bst': typeof BstRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/bst'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/bst'
  id: '__root__' | '/' | '/bst'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BstRoute: typeof BstRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/bst': {
      id: '/bst'
      path: '/bst'
      fullPath: '/bst'
      preLoaderRoute: typeof BstRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BstRoute: BstRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
